name: Lint

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

jobs:
  lint:
    runs-on: ubuntu-latest  # Selecciona el sistema operativo adecuado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --ext .js .
