name: Static Analysis

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

jobs:
  static-analysis:
    runs-on: ubuntu-latest  # Selecciona el sistema operativo adecuado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          git fetch --unshallow --tags
          sonar-scanner
